INFERANALYZE = '/usr/local/lib/infer/infer/bin/infer-analyze' --results-dir '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out' 

CLUSTERS=cl1 cl2 cl3 cl4 cl5 cl6 cl7 cl8 cl9 cl10 cl11 cl12 cl13 cl14 cl15 cl16 cl17 cl18 cl19 cl20 cl21 cl22 cl23 cl24 cl25 cl26 cl27 cl28 cl29 cl30 cl31 cl32 cl33 cl34 cl35 cl36 cl37 cl38 cl39 cl40 cl41 cl42 cl43 cl44 cl45 cl46 cl47 cl48 cl49 cl50 cl51 cl52 cl53 cl54 cl55 cl56 cl57 cl58 cl59 cl60 cl61 cl62 cl63 cl64 cl65 cl66 cl67 cl68 cl69 cl70 cl71 cl72 cl73 cl74 cl75 cl76 cl77 cl78 cl79 cl80 cl81 cl82 cl83 

default: test

all: test

test: $(CLUSTERS)
	@echo

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/EmojiconGridView.java.67694ec25caeae650ca4360ee978747f
cl1: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl1.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/EmojiComponent.java.6389bee97cd114a87beff8d6595a12d3
cl2: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl2.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.f5a5d80c1944fcedfd0451eb5b9a8256
cl3: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl3.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.68ebf536d5223879951f4f6ea2d7d7ea
cl4: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl4.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.0715e79de56958db3e17c1de4184b15f
cl5: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl5.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.38d5a7c5fea8ca1fa1ba150c189aa82d
cl6: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl6.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/EmojiconAdapterTextView.java.f44f46ab8b1d6cc1fe51779b2eeac3e1
cl7: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl7.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.38e32068e795531446a86d328ba11be2
cl8: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl8.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/Objects.java.206223f75d0fce8823a20d574a83902d
cl9: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl9.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/EmojiconRecentsGridFragment.java.e91a63f91f5df024c58c85947dc88804
cl10: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl10.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.d4300d250254907104597b85c79e1f73
cl11: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl11.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/EmojisTable.java.626d11abe3c27578a8a0793b3c0b8461
cl12: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl12.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.19c21722466e1c976091aaa640d74f76
cl13: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl13.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.d80031b7ec57dd20efcf80323ec67353
cl14: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl14.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/EmojiconAdapter.java.bb9babec42b9e2a289fee410c2f5f362
cl15: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl15.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/Emojicon.java.ef24af0ae526e95796a472b4b1cf7722
cl16: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl16.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.200e5cc4c928cfcd364f06c368503205
cl17: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl17.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/EmojiconGridFragment.java.ec55b6523a9f54fc3a3dd4f0a7efd70b
cl18: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl18.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/EmojiComponent.java.52cc03e938943b573a5bff1eefa50fb7
cl19: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl19.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.a9b57fda772e1bc2c67aa24084acbb9d
cl20: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl20.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.a4740ccd057acb4555daaa29f191ee04
cl21: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl21.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.fbcb8bc1dc8379776094c3fec6362ffb
cl22: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl22.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.5587d1659be0d73cca1b1aa12f95e414
cl23: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl23.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/EmojiconPage.java.9f316673537297845616b5c7bed34304
cl24: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl24.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/EmojiconAdapterString.java.ea27deffa95837f2b5627e583f195972
cl25: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl25.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.2b7073fdddbf9f8da8f73d1337b4c4fa
cl26: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl26.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.cab30fcc75ac799aab80ccfd827c75ae
cl27: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl27.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.e4998a5b1b6add3527df0fa40bc3a015
cl28: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl28.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.f7ffe43d69bc283b85990ffe451d60e2
cl29: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl29.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/EmojiconRecentsManager.java.7f5072f7b5c70c54950f959db896963d
cl30: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl30.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/Symbols.java.763d3f08d52d96432c6616e5b705d2f5
cl31: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl31.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.ffd8d1232393b78ec289f19ab6827df3
cl32: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl32.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.6203a2683f44be5044f59325189a5979
cl33: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl33.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.e7cc35f4bbd25be9b3e1a2d559f6def0
cl34: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl34.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/EmojiconsFragment.java.b2619ac94c88a07ce41a54e93bdea856
cl35: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl35.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.2a65eaceef5e0a8290beeed4abeed6a0
cl36: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl36.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/EmojiconEditText.java.c77bd6ac381f71f0193f6b7e88380ae2
cl37: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl37.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.fddfe8b0ac958aa91f6cd41fef883ed5
cl38: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl38.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.cc4ec3a4540846f1b51843d9880d3cb8
cl39: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl39.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/People.java.5fbe745d2ffed9bda4a275186025663d
cl40: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl40.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/BuildConfig.java.e1df913fc79e15d117453b1f51790885
cl41: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl41.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.7f2f9fbb89c4e22442f0bae24c9a1ffd
cl42: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl42.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/Nature.java.ff9cf3ba63281e9feab1470c2573600e
cl43: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl43.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.9f91544e63e57034878d9ecc3cc28c21
cl44: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl44.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.349e62c3dc16dde4a22e5ead7f7997ae
cl45: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl45.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/EmojiconAdapterVerticalRV.java.3ac8c954c812bf56d0f74fd13950f9e4
cl46: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl46.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/EmojiconMultiAutoCompleteTextView.java.d2ac6ce29cbda6db55593e7dd5170e1a
cl47: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl47.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.3b29408800d5a59bb3e4c615c4d3d3ab
cl48: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl48.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.e2bd8759f80d4dd1665ac01746b9e228
cl49: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl49.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/EmojiconRecents.java.8c9dcfcfffbc554c696e7e1d1a4b2f56
cl50: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl50.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.b73bd960222d3ffd256abd0711d81956
cl51: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl51.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.6dfbb4a918059a9663c6153537379de6
cl52: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl52.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/EmojiconAdapterThread.java.f51d954e68de04a0568a260f936be82b
cl53: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl53.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.323c05b93d455c338af78e3bb0a35d1f
cl54: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl54.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.45bd9002beff536d32337525905a2ecb
cl55: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl55.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/EmojiconTextView.java.bba911cb0e60a52a358e6cdd07b0c43d
cl56: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl56.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/EmojiconGridFragmentUsingLitho.java.034c11f3c1a9b7ce29b0e063d83693e3
cl57: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl57.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.2259a35f8e2e1e98fd54173aac63919d
cl58: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl58.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.1bfb5134a77165957f180670546ea387
cl59: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl59.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.84981e5db1aa32dfbe92204babd62d96
cl60: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl60.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.db9fe244a8b3a79c75e280e84017099f
cl61: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl61.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/EmojiconSpan.java.507cf4193d805419beebc3f90b9612c0
cl62: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl62.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.996c7d1d1edc370a44d6639fdaa9d802
cl63: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl63.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/EmojiconsView.java.d325941171954bda61fe0d4a0889aaad
cl64: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl64.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/Utils.java.6d791128a5bd8d98719475429da8d323
cl65: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl65.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.a2ad9f01f9dbcc2aa40d27491793ba9c
cl66: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl66.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/EmojiconAdapterGridRV.java.5b35f063be2055a0b63c34107a0fcbcd
cl67: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl67.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.305e28bf1d701e2de11c4a5bb915e8d1
cl68: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl68.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.476c23bb85b81e2066b8a0653025c8f9
cl69: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl69.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.37434d7274e41f2f0bb437df214358e2
cl70: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl70.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/Places.java.d75c50019df4545bd04a08b26f864157
cl71: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl71.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.b503302c56d5683bec54085d20fbc1e0
cl72: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl72.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.212339949fa38db7f9de9d9137442dcc
cl73: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl73.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.dac9a22148755d47ede6f65718441cb1
cl74: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl74.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.61ea272c6bd46abe1e0946f8317826ed
cl75: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl75.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.01cd80d9e6ef93285aa09d1977ab5a1d
cl76: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl76.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.aaf7363e301473229ce11b64b625c261
cl77: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl77.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.a9ba31c95849279538f19a9413d7f493
cl78: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl78.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/EmojiComponentSpec.java.82a8940eae1bd1eb7a95bb09e5346f26
cl79: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl79.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/BuildConfig.java.d061a99b064bd9ce5262a1c6d38aad31
cl80: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl80.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/EmojiconHandler.java.d2ad93bd28b05e55c8473b01ee98d51b
cl81: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl81.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.2b5d0cfd9251911ef3882af9582bc2a4
cl82: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl82.cluster'
	@touch $@

#/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/captured/R.java.2670cc6b4942abc05a398e4f3f011bec
cl83: 
	$(INFERANALYZE) --cluster '/home/cpu10661/AndroidStudioProjects/emojicon-master/infer-out/multicore/xcl83.cluster'
	@touch $@


clean:
	rm -f $(CLUSTERS)
